name: Code Quality Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  codeQuality:
    name: Eslint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check with eslint
        id: eslint-run
        run: |
          npm run lint
      - name: Build with Vite
        run: npm run build
      - name: Add Hacktberfest labels
        uses: actions/github-script@v4
        if: ${{ steps.eslint-run.outcome == 'success' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['hacktoberfest-accepted']
            })
